### PR TITLE
fix: Conform counting of "uses" of an indent to the documentation

### LINKED ISSUE #33: Occurrences of indent sizes are not counted as per documentation.
Consider the attached example file. It is constructed (somewhat artificially in this case, but it comes from an actual source file I am working with in another project) to have exactly one occurrence of a single-space indentation change, at least as I interpret the documentation of this package. On the other hand, it has eleven occurrences of a four-space indentation change, and I think most any coder would consider it to have an indentation size of 4 spaces.

Yet currently detect-indent computes it to have an indent size of 1 space. The statistics gathered in makeIndentsMap are:
```
{ 's3' => [ 1, 0 ], 's1' => [ 22, 21 ], 's4' => [ 15, 4 ] }
```
The difficulty appears to be that on each of the many lines at the same indent level just after the 1-space indentation change, the `usedCount` (i.e., first entry) of the value for the `s1` key is being incremented, which appears to contradict the documentation.

I will file a PR adding this as a test case, with a fix for the issue.
[long-repeat.txt](https://github.com/sindresorhus/detect-indent/files/9466455/long-repeat.txt)

### PR DESCRIPTION
**Pull request by gwhitney**
Resolves #33.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you update the algorithm section with the new behavior? https://github.com/sindresorhus/detect-indent#algorithm

**Comment by gwhitney** [comment]
Sorry if I wasn't clear; the prior code was not implementing the algorithm as described (it was updating the use count too often), and the fix is to modify the code so that it _is_ implementing the described algorithm, which seems perfectly reasonable. So with this PR, the algorithm and code are, I believe, brought into sync and so there should not be any changes needed to the documentation. Thanks for considering this PR.

**Comment by gwhitney** [comment]
Please let me know if there's anything else I can do to help get this bugfix merged and a fixed version published, as downstream there is buggy behavior (when rewriting package manifests) in the widely-used `pnpm` package manager for Node as a result, and I would like to get that problem with pnpm resolved. Thanks so much!

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by gwhitney** [comment]
Thank _you_!

**Pull request merged**
